### ISSUE TITLE
TESTING RESULTS TAB: Is something missing in Laser Measurement?

### ISSUE THREAD

**Issue by rdopsovic** [jordan-clark/SAGA#12]

**Comment by jordan-clark** [comment]
@rdopsovic I updated the site to check for values, however, when you go to view the actual report I am not getting any data back. I will investigate.

**Comment by jordan-clark** [comment]
This is a matter of updating the table with the correct column mappings.

How should we display this data - There are over 100 columns?

**Comment by rdopsovic** [comment]
Attached (via email, not sure how to attached in github) is the spreadsheet with the data.  The columns K through DF are the size of the microsieve (or whatever it's called).  I believe the reported number is the percent passing though that sieve.

Is it a problem showing all of the columns?  It's a lot of data, but I think that's how they are used to seeing it.  Or we could filter the columns, like - "show only results between 0.02 and 0.035566"

**Comment by jordan-clark** [comment]
No there isn't a problem. It's just not going to look very nice. But I guess the data is what's most important.

**Comment by jordan-clark** [comment]
Completed and published to dev.
