### ISSUE TITLE
TESTING RESULTS: Move "Close" button to the top of the report.

### ISSUE THREAD

**Issue by rdopsovic** [jordan-clark/SAGA#18]

**Comment by jordan-clark** [comment]
completed.

**Comment by rdopsovic** [comment]
Classification: UNCLASSIFIED
Caveats: NONE

Just an FYI.. I am working on updating those attributes.  I click the "calculate" button hours ago and it's still processing.

Rose Dopsovic
Sr. GIS Coordinator
Bowhead Professional Solutions for
The Spatial Data Branch, US Army Corps of Engineers Mobile District
251.680.4047


-----Original Message-----
