### ISSUE TITLE
TESTING RESULTS: Some reports require a few more fields.  

### ISSUE THREAD

**Issue by rdopsovic** [jordan-clark/SAGA#20]
Some reports require a few more fields.  E.g., Solid-Phase Acute Toxicity test needs Species, Name of Test, Replicate, etc.

Check the respective Views for the data categories. (e.g., A101_BIOSOLIDP_RESULTS_DESC is for the Solid Phase Acute Toxicity testing results)

**Comment by jordan-clark** [comment]
Might need some cleaning up on these. Closing for now.
