### ISSUE TITLE
MONITORING TAB: Create page (River Sediment Monitoring Only)

### ISSUE THREAD

**Issue by rdopsovic** [jordan-clark/SAGA#21]
Data Description for SITE_MONITORING_RESULTS

One tab show all fields withing table; add 4 more "calculated" fields for viewing purposes.

Here are the calculation (for reporting purposes) to generate the values:
DAILY_WATER_DISCHARGE_CFD = [DAILY_WATER_DISCHARGE_CFS] *60*60*24
DAILY_TOTAL_SED_DISCHARGE_MTD =  [DAILY_TOTAL_SED_DISCHARGE_STD] * 0.90718474
DAILY_SAND_DISCHARGE_MTD = [DAILY_WATER_DISCHARGE_CFS]*0.9071874
DAILY_WATER_DISCHARGE_CMD = ([DAILY_WATER_DISCHARGE_CFS] *60*60*24)*0.0283168466

Field labels:
Date (mm/dd/yyyy)
Daily total sediment discharge (short tons/day)
Daily sand discharge (short tons/day)
Daily water discharge (cubic feet per second)
Daily water discharge (cubic feet per day)
Daily total sediment discharge (metric tons/day)
Daily sand discharge (metric tons/day)
Daily water discharge (cubic meters per day)

**Comment by jordan-clark** [comment]
So, when clicking on the RSM points close the where the MS river connects with the gulf, you will notice some lag while loading the popup. It's because there is so much data associated.

**Comment by rdopsovic** [comment]
Statigraphy tab still appears for the riverine sites.  Stratigraphy tab should only be visible for non-gage/non-MSA sites.

**Comment by jordan-clark** [comment]
Yes, I published that update to development yet.
