### ISSUE TITLE
SUB-SAMPLES TAB: If only one top/bottom value is known, do not calculate a thickness.

### ISSUE THREAD

**Issue by rdopsovic** [jordan-clark/SAGA#22]

**Comment by jordan-clark** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/2112737/7187778/a89dd8d8-e438-11e4-852c-970d6e690363.jpg)

**Comment by jordan-clark** [comment]
@rdopsovic - altered code to check both bottom and top depth for null values.
