### ISSUE TITLE
For laser measurements, add alias names to column header.

### ISSUE THREAD

**Issue by rdopsovic** [jordan-clark/SAGA#35]

**Comment by jordan-clark** [comment]
What are the alias names for these columns? it looks like to me the alias is the same as the current label.

**Comment by rdopsovic** [comment]
There are decimal places and the word size shouldn't be there. I think I put the labels somewhere on github.

**Comment by jordan-clark** [comment]
Okay, so for instance SIZE_002244 label should be 0.02244. What about SIZE_355655882  - would that be 3.55655882?

**Comment by jordan-clark** [comment]
Completed.
