### ISSUE TITLE
Subsample detection should be pulled from SITE_SAMPLE_SUBSAMPLES table.  I believe the A101_SUBSAMPLES_AVAILABLE table should be deleted.

### ISSUE THREAD

**Issue by rdopsovic** [jordan-clark/SAGA#37]

**Comment by jordan-clark** [comment]
Completed.

**Comment by rdopsovic** [comment]
Classification: UNCLASSIFIED
Caveats: NONE

I just noticed something in the database.  For the riverine data the % finer values in PHYSICAL_DISTRIB_RESULTS need to have a scale of at least 3 or switch to a text field so we don't have worry about dropping values.  I'm going to need to remove and reload the riverine data since all of the values were truncated that had more than one decimal place.

It should affect anything your doing, but I'm putting it on my to-do list.

Rose Dopsovic
Sr. GIS Coordinator
Bowhead Professional Solutions for
The Spatial Data Branch, US Army Corps of Engineers Mobile District
251.680.4047


-----Original Message-----

**Comment by jordan-clark** [comment]
Classification: UNCLASSIFIED
Caveats: NONE

Okay, thanks.

Jordan Clark


-----Original Message-----

**Comment by rdopsovic** [comment]
Classification: UNCLASSIFIED
Caveats: NONE

Oop.  I didn't realize I sent it to your other email.

Rose Dopsovic
Sr. GIS Coordinator
Bowhead Professional Solutions for
The Spatial Data Branch, US Army Corps of Engineers Mobile District
251.680.4047


-----Original Message-----
