### ISSUE TITLE
LOCATION: Not sure if Date field on the tab is pulling the correct value

### ISSUE THREAD

**Issue by rdopsovic** [jordan-clark/SAGA#42]

**Comment by jordan-clark** [comment]
Fixed.

**Comment by rdopsovic** [comment]
Classification: UNCLASSIFIED
Caveats: NONE

From the meeting in July, Jim Lewis asked how we can attached metadata to the individual sites.  Could we add one more field to the location tab to link to metadata?  I can add this field to SITE_SAMPLE_LOCATIONS.  The value from the field, e.g. {90C9DF75-62E7-41F4-A5E3-DE5F1971179C}, would be used to build a link to Metadata Manager
http://metadata.usace.army.mil/geoportal/catalog/search/resource/details.page?uuid=%7B90C9DF75-62E7-41F4-A5E3-DE5F1971179C%7D

If a values exists for the sdsMetadataID field in SITE_SAMPLE_LOCATIONS, that value on the form would be "View Metadata" with a hyperlink.


Rose Dopsovic
Sr. GIS Coordinator
Bowhead Professional Solutions for
The Spatial Data Branch, US Army Corps of Engineers Mobile District
251.680.4047


-----Original Message-----
